### PR TITLE
Fixed control surface colors

### PR DESCRIPTION
**Pull request by Atknssl**
Thanks for the great tool. It's really useful for visualizing flight data.

However, I found a small bug in the code that makes all control surface colors the same as the first control surface color. This causes problems when I use a different model with different control surface colors. I fixed this problem in this pull request.

### CODE REVIEW

**Comment by Atknssl** [comment]
Additionally, I can run the code in version 2015b without any problem. Maybe the version check in the code can also be updated.

**Comment by jediPhD** [comment]
I want to create a 3D animation for the Cessna 500. However, in the run_animation.m script, the line 'fc = '3attitude_step_GT0PLE_normal'; load(strcat('mat_files/',fc,'.mat'))' references a .mat file that I cannot provide, so I can't run the animation. I am new to working on these topics and would appreciate any help you can offer. First, I ran the convert.m script, then I ran the run_animation.m script, but I did not get any results. Could you please explain what I need to do?

**Comment by Ro3code** [comment]
Just go to the examples folder, and execute any of the run_aninamtion_*.m
files

[image: image.png]

Cheers,
Rodney

**Comment by Atknssl** [comment]
@Ro3code can you review this pull request?

**Pull request merged**
